mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.jh.cavycms.domain
server:
  port: 8081
  servlet:
    context-path: /cavy
spring:
  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: cavy-cms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: 123456
    url: jdbc:mysql://localhost:3306/cavy-cms?serverTimezone=UTC
    username: root
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
