mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.jh.cavycms.domain
server:
  port: 8081
  servlet:
    context-path: /cavy
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
  favicon:
      enabled: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static,classpath:/resources/
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: cavy-cms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/cavy-cms?serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false # 如果为true，则分页参数无效的情况下，则查询全部数据
  supportMethodsArguments: true
  params: count=countSql